### ISSUE TITLE
eagle cannot print multiple variables at once

### ISSUE THREAD

**Issue by TheIonDev** [DarthEggo/AmericaScript#2]
I don´t know if this is intentional, but if you change the line
```globalEnv.def("eagle", function(txt){ console.log(txt); });```
to
```globalEnv.def("eagle", function(...txt) { console.log(...txt); });```
it can print out multiple variables at once

**Comment by DarthEggo** [comment]
Alright, that works. Do you want to make a pull request so you can get credit for it?
